[package]
name = "amo"
version = "0.1.0"
edition = "2024"

[dependencies]
zbus = "5"
zbus_polkit = "5.0.0"
tokio = { version = "1", features = ["full"] }
oma-refresh = { git = "https://github.com/aosc-dev/oma", package = "oma-refresh", branch = "master" }
oma-pm = { git = "https://github.com/aosc-dev/oma", package = "oma-pm", branch = "oma-pm-check-current-in-tokio-rt" }
anyhow = "1"
apt-auth-config = { path = "../oma/apt-auth-config", package = "apt-auth-config" }
oma-utils = { path = "../oma/oma-utils", package = "oma-utils", features = [
    "dpkg",
] }
reqwest = "0.13"
oma-fetch = { git = "https://github.com/aosc-dev/oma", package = "oma-fetch", branch = "master" }
serde = { version = "1", features = ["derive"] }
futures = "0.3"
serde_json = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
reqwest-middleware = "0.5.2"
os_pipe = "1"

[dev-dependencies]
futures-util = "0.3.32"
